services:
  postgres:
    image: postgres:18.1
    container_name: postgres_compensacao_finan
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - compensacao_scraper_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  etl_compensacao_finan:
    build: .
    image: etl_compensacao_finan:latest
    container_name: scraper_compensacao_finan
    command: ['python', 'etl.py']
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - compensacao_scraper_net

volumes:
  pgdata:

networks:
  compensacao_scraper_net:
    driver: bridge
